version: '3.8'

services:

  # Base de Datos MySQL
  db:
    image: mysql:8.0
    container_name: pachangapp-db
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: pachangapp
      MYSQL_USER: pachangapp_user
      MYSQL_PASSWORD: pachangapp_pass
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - pachangapp-net

  # Backend Spring Boot (requiere haber hecho mvn package antes)
  backend:
    build: ./backend
    container_name: pachangapp-backend
    ports:
      - "8091:8091"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://db:3306/pachangapp
      SPRING_DATASOURCE_USERNAME: pachangapp_user
      SPRING_DATASOURCE_PASSWORD: pachangapp_pass
      PACHANGAPP_AI_KEY: ${PACHANGAPP_AI_KEY:-}
      PACHANGAPP_AI_URL: ${PACHANGAPP_AI_URL:-https://api.openai.com/v1/chat/completions}
      PACHANGAPP_AI_MODEL: ${PACHANGAPP_AI_MODEL:-gpt-4o-mini}
    depends_on:
      - db
    networks:
      - pachangapp-net

  # Frontend React/Vite servido con Nginx
  frontend:
    build: ./frontend
    container_name: pachangapp-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - pachangapp-net

  # n8n — Plataforma de automatización de flujos
  n8n:
    image: docker.n8n.io/n8nio/n8n
    container_name: pachangapp-n8n
    ports:
      - "5678:5678"
    environment:
      - N8N_HOST=34.197.214.53
      - N8N_PORT=5678
      - N8N_PROTOCOL=http
      - WEBHOOK_URL=http://34.197.214.53:5678/
    volumes:
      - n8n_data:/home/node/.n8n
    networks:
      - pachangapp-net


volumes:
  mysql_data:
  n8n_data:

networks:
  pachangapp-net:
    driver: bridge