apiVersion: v1
kind: Secret
metadata:
  name: pachangapp-secrets
type: Opaque
data:
  # Todos los valores en Base64 (los de arriba si no los cambias)
  db-name: cGFjaGFuZ2FwcA==
  db-user: cGFjaGFuZ2FwcF91c2Vy
  db-password: cGFjaGFuZ2FwcF9wYXNz
  db-root-password: cm9vdA==