spring.application.name=backend
spring.datasource.url=jdbc:mysql://localhost:3306/pachangapp_db?createDatabaseIfNotExist=true&useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true
spring.datasource.username=root
spring.datasource.password=
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect
spring.sql.init.mode=never
spring.jpa.defer-datasource-initialization=true

server.port=8091

# JWT Config
pachangapp.app.jwtSecret=pachangappSecretKeyWhichMustBeAtLeast256BitsLongForHmacSha256
pachangapp.app.jwtExpirationMs=86400000
pachangapp.app.baseUrl=https://api.pachangapp.es

# n8n Webhook Config
pachangapp.n8n.webhookUrl=https://n8n.pachangapp.es/webhook/pachangapp-emails

# Email Config (Gmail) - Mantener para reseteo de contraseña
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dev.ibrahim.ma@gmail.com
spring.mail.password=qwzyksdrcwvctayk
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# File Config
pachangapp.app.uploadDir=uploads

# External APIs
pachangapp.app.weatherApiKey=TU_API_KEY_AQUI
pachangapp.app.openaiApiKey=TU_OPENAI_KEY_AQUI
pachangapp.app.googleClientId=922573748283-18kdun9e7vnjf8s3lnpdidbu13qmipt7.apps.googleusercontent.com

# Multipart Config
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB
